# StellarOps Grafana Secrets
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  labels:
    app: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: stellarops
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: "admin"
  GF_SECURITY_ADMIN_PASSWORD: "stellarops"
